import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

import SignUpModal from './components/SignUpModal';
import SignInModal from './components/SignInModal';
import AuthContext from './contexts/AuthContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gray-100 min-h-screen w-screen">
          <AuthContext>
            <div className="max-w-screen-2xl m-auto bg-white">
              <nav className="bg-white p-2 flex justify-between">
                <Link href="/" className="font-bold text-gray-700 text-2xl">
                  OpenTable
                </Link>
                <div>
                  <div className="flex">
                    <SignInModal />
                    <SignUpModal />
                  </div>
                </div>
              </nav>
              {children}
            </div>
          </AuthContext>
        </div>
      </body>
    </html>
  );
}
