import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-gray-100 min-h-screen w-screen">
          <div className="max-w-screen-2xl m-auto bg-white">
            <nav className="bg-white p-2 flex justify-between">
              <Link href="/" className="font-bold text-gray-700 text-2xl">
                OpenTable
              </Link>
              <div>
                <div className="flex">
                  <button className="bg-blue-400 text-white border p-1 px-4 rounded mr-3">
                    Sign in
                  </button>
                  <button className="border p-1 px-4 rounded">Sign up</button>
                </div>
              </div>
            </nav>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
